insert into COACHING (ID, COMPLETION_DATE,COURSE_NAME,DONE,FIRST_NAME)
VALUES (100,current_date,'LEARN CORE JAVA',TRUE,'MAYANK');
insert into COACHING (ID, COMPLETION_DATE,COURSE_NAME,DONE,FIRST_NAME)
VALUES (200,current_date,'LEARN SPRING FRAMEWORK',FALSE,'RAHUL');
insert into COACHING (ID, COMPLETION_DATE,COURSE_NAME,DONE,FIRST_NAME)
VALUES (300,current_date,'LEARN SQL',FALSE,'HARSHIT');